In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/Master_data/Master_dataset.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [4]:
print(df.columns)

Index(['distCode_x', 'distName_x', 'officeCode_x', 'officeName_x', 'shopNo',
       'month_x', 'year_x', 'noOfRcs', 'noOfTrans', 'riceAfsc', 'riceFsc',
       'riceAap', 'wheat', 'sugar', 'totalAmount', 'otherShopTransCnt',
       'riceAap_available', 'wheat_available', 'distCode_y', 'distName_y',
       'officeCode_y', 'officeName_y', 'rcNfsaAay', 'unitsNfsaAay',
       'rcNfsaPhh', 'unitsNfsaPhh', 'totalRcNfsa', 'totalUnitsNfsa',
       'rcStateAay', 'unitsStateAay', 'rcStatePhh', 'unitsStatePhh',
       'rcStateAap', 'unitsStateAap', 'totalRcState', 'totalUnitsState',
       'totalRcs', 'totalUnits', 'units', 'gasCylinders', 'distCode',
       'distName', 'officeCode', 'officeName', 'address', 'longitude',
       'latitude', 'fpsStatus', 'fpsType', 'dateTime', 'year_y', 'month_y',
       'day'],
      dtype='object')

In [5]:
df.shape

(482257, 53)

In [6]:

print(df.isnull().sum().value_counts())

0       40
4193    13
Name: count, dtype: int64

In [7]:
missing_cols = df.columns[df.isnull().sum() == 4193]

print(missing_cols.tolist())

['distCode', 'distName', 'officeCode', 'officeName', 'address', 'longitude', 'latitude', 'fpsStatus', 'fpsType', 'dateTime', 'year_y', 'month_y', 'day']

In [8]:
df.drop_duplicates(inplace=True)

print("Duplicate rows removed")

Duplicate rows removed

In [9]:
df.isnull().sum().sort_values(ascending=False)

fpsType              4193
day                  4193
fpsStatus            4193
latitude             4193
longitude            4193
dateTime             4193
year_y               4193
month_y              4193
distCode             4193
address              4193
officeName           4193
officeCode           4193
distName             4193
month_x                 0
year_x                  0
noOfRcs                 0
distCode_x              0
distName_x              0
officeCode_x            0
officeName_x            0
shopNo                  0
officeCode_y            0
distName_y              0
distCode_y              0
wheat_available         0
riceAap_available       0
otherShopTransCnt       0
totalAmount             0
sugar                   0
wheat                   0
riceAap                 0
riceFsc                 0
riceAfsc                0
noOfTrans               0
officeName_y            0
unitsNfsaAay            0
rcNfsaAay               0
totalRcs                0
totalUnitsState         0
totalRcState            0
unitsStateAap           0
rcStateAap              0
unitsStatePhh           0
rcStatePhh              0
unitsStateAay           0
rcStateAay              0
totalUnitsNfsa          0
totalRcNfsa             0
unitsNfsaPhh            0
rcNfsaPhh               0
units                   0
gasCylinders            0
totalUnits              0
dtype: int64

In [10]:
df['fpsType'] = df['fpsType'].fillna('Inactive Shop')

In [11]:
df['fpsType'].value_counts(dropna=False)

fpsType
Normal Shop      478064
Inactive Shop      4193
Name: count, dtype: int64

In [12]:
df.drop(columns=['day'], inplace=True)

In [13]:
'day' in df.columns

False

In [14]:
df['fpsStatus'] = df['fpsStatus'].fillna('Inactive')

In [16]:
df['fpsStatus'].value_counts(dropna=False)

fpsStatus
Active      478064
Inactive      4193
Name: count, dtype: int64

In [17]:
df['distCode'] = df['distCode'].fillna(df['distCode_x'])

In [19]:
df['distCode'].isnull().sum()

np.int64(0)

In [20]:
df['distName'] = df['distName'].fillna(df['distName_x'])

In [21]:
df['distName'].isnull().sum()

np.int64(0)

In [22]:
df['officeCode'] = df['officeCode'].fillna(df['officeCode_x'])

In [23]:
df['officeCode'].isnull().sum()

np.int64(0)

In [24]:
df['officeName'] = df['officeName'].fillna(df['officeName_x'])

In [25]:
df['officeName'].isnull().sum()

np.int64(0)

In [26]:
drop_cols = [
    'distCode_x',
    'distName_x',
    'officeCode_x',
    'officeName_x',
    'distCode_y',
    'distName_y',
    'officeCode_y',
    'officeName_y'
]

df.drop(columns=drop_cols, inplace=True)

In [27]:
df.isnull().sum().sort_values(ascending=False)

longitude            4193
address              4193
year_y               4193
month_y              4193
dateTime             4193
latitude             4193
noOfTrans               0
riceAfsc                0
shopNo                  0
month_x                 0
year_x                  0
noOfRcs                 0
otherShopTransCnt       0
totalAmount             0
sugar                   0
wheat                   0
riceAap                 0
riceFsc                 0
riceAap_available       0
wheat_available         0
rcStateAay              0
unitsStateAay           0
rcNfsaAay               0
unitsNfsaAay            0
rcNfsaPhh               0
unitsNfsaPhh            0
totalRcNfsa             0
totalUnitsNfsa          0
totalUnitsState         0
totalRcState            0
unitsStateAap           0
rcStateAap              0
unitsStatePhh           0
rcStatePhh              0
totalRcs                0
totalUnits              0
officeName              0
officeCode              0
distName                0
distCode                0
gasCylinders            0
units                   0
fpsStatus               0
fpsType                 0
dtype: int64

In [28]:
print(df[['year_x', 'year_y']].head())

print(df[['month_x', 'month_y']].head())

   year_x  year_y
0    2023  2025.0
1    2023  2025.0
2    2023  2025.0
3    2023  2025.0
4    2023  2025.0
   month_x  month_y
0       10      7.0
1       10      7.0
2       10      7.0
3       10      7.0
4       10      7.0

In [29]:
(df['year_x'] == df['year_y']).value_counts(dropna=False)

False    396403
True      85854
Name: count, dtype: int64

In [30]:
(df['month_x'] == df['month_y']).value_counts(dropna=False)

False    448129
True      34128
Name: count, dtype: int64

In [31]:
df.rename(columns={
    'year_x': 'year',
    'month_x': 'month'
}, inplace=True)

In [32]:
df['dateTime'] = pd.to_datetime(df['dateTime'], errors='coerce')

In [33]:
df.drop(columns=['address'], inplace=True)

In [34]:
df[['latitude','longitude']].describe()

            latitude      longitude
count  478064.000000  478064.000000
mean       17.740837      78.854286
std         0.824712       1.435307
min         0.283333       1.300000
25%        17.183106      78.263737
50%        17.629694      78.732635
75%        18.338446      79.500736
max        19.880502      81.263470

In [35]:
df['latitude'] = df['latitude'].fillna(
    df.groupby('shopNo')['latitude'].transform('median')
)

df['longitude'] = df['longitude'].fillna(
    df.groupby('shopNo')['longitude'].transform('median')
)

In [36]:
df['latitude'] = df['latitude'].fillna(df['latitude'].median())
df['longitude'] = df['longitude'].fillna(df['longitude'].median())

In [37]:
df.isnull().sum().sort_values(ascending=False)

month_y              4193
year_y               4193
dateTime             4193
noOfRcs                 0
noOfTrans               0
riceAfsc                0
riceFsc                 0
riceAap                 0
shopNo                  0
month                   0
year                    0
totalAmount             0
sugar                   0
wheat                   0
otherShopTransCnt       0
unitsNfsaAay            0
riceAap_available       0
wheat_available         0
rcNfsaAay               0
totalUnitsNfsa          0
rcStateAay              0
unitsStateAay           0
rcStatePhh              0
unitsStatePhh           0
rcNfsaPhh               0
unitsNfsaPhh            0
totalRcNfsa             0
totalRcState            0
unitsStateAap           0
rcStateAap              0
totalUnitsState         0
gasCylinders            0
totalRcs                0
totalUnits              0
units                   0
officeCode              0
distName                0
distCode                0
officeName              0
fpsStatus               0
latitude                0
longitude               0
fpsType                 0
dtype: int64

In [38]:
df.drop(columns=['month_y', 'year_y'], inplace=True)

In [39]:
df.rename(columns={
    'month_x': 'month',
    'year_x': 'year'
}, inplace=True)

In [40]:
df.isnull().sum().sort_values(ascending=False)

dateTime             4193
month                   0
year                    0
noOfRcs                 0
noOfTrans               0
riceAfsc                0
riceFsc                 0
riceAap                 0
shopNo                  0
wheat                   0
sugar                   0
otherShopTransCnt       0
totalAmount             0
wheat_available         0
rcNfsaAay               0
unitsNfsaAay            0
riceAap_available       0
unitsNfsaPhh            0
totalRcNfsa             0
totalUnitsNfsa          0
rcStateAay              0
unitsStateAay           0
rcStatePhh              0
unitsStatePhh           0
rcNfsaPhh               0
rcStateAap              0
unitsStateAap           0
totalUnitsState         0
totalRcState            0
totalUnits              0
units                   0
gasCylinders            0
totalRcs                0
distCode                0
distName                0
officeName              0
officeCode              0
longitude               0
latitude                0
fpsStatus               0
fpsType                 0
dtype: int64

In [41]:
df['dateTime'] = df['dateTime'].fillna(method='ffill')

C:\Users\HP\AppData\Local\Temp\ipykernel_11308\3906305549.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['dateTime'] = df['dateTime'].fillna(method='ffill')

In [42]:
df.isnull().sum().sort_values(ascending=False)

shopNo               0
month                0
year                 0
noOfRcs              0
noOfTrans            0
riceAfsc             0
riceFsc              0
riceAap              0
wheat                0
sugar                0
totalAmount          0
otherShopTransCnt    0
riceAap_available    0
wheat_available      0
rcNfsaAay            0
unitsNfsaAay         0
rcNfsaPhh            0
unitsNfsaPhh         0
totalRcNfsa          0
totalUnitsNfsa       0
rcStateAay           0
unitsStateAay        0
rcStatePhh           0
unitsStatePhh        0
rcStateAap           0
unitsStateAap        0
totalRcState         0
totalUnitsState      0
totalRcs             0
totalUnits           0
units                0
gasCylinders         0
distCode             0
distName             0
officeCode           0
officeName           0
longitude            0
latitude             0
fpsStatus            0
fpsType              0
dateTime             0
dtype: int64

In [43]:
df.head(10)
df.tail(10)

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,gasCylinders,distCode,distName,officeCode,officeName,longitude,latitude,fpsStatus,fpsType,dateTime
482247,4612003,9,2024,188,190,455.0,3936.0,0.0,0.0,0.0,...,0,982.0,Narayanpet,982012.0,Krishna,77.401576,16.387638,Active,Normal Shop,2025-07-03 14:44:03.763814+05:30
482248,4612004,9,2024,293,293,875.0,6072.0,0.0,0.0,0.0,...,0,982.0,Narayanpet,982012.0,Krishna,77.356179,16.447972,Active,Normal Shop,2025-07-03 14:44:03.763814+05:30
482249,4612005,9,2024,533,533,1640.0,10552.0,0.0,0.0,0.0,...,0,982.0,Narayanpet,982012.0,Krishna,77.389511,16.462161,Active,Normal Shop,2025-07-03 14:44:03.763814+05:30
482250,4612006,9,2024,712,712,1610.0,14954.0,0.0,0.0,0.0,...,0,982.0,Narayanpet,982012.0,Krishna,77.383842,16.417320,Active,Normal Shop,2025-07-03 14:44:03.763814+05:30
482251,4612007,9,2024,795,797,1855.0,16428.0,0.0,0.0,0.0,...,0,982.0,Narayanpet,982012.0,Krishna,77.385501,16.415811,Active,Normal Shop,2025-07-03 14:44:03.763814+05:30
482252,4612008,9,2024,316,316,770.0,6840.0,0.0,0.0,0.0,...,0,982.0,Narayanpet,982012.0,Krishna,77.362910,16.475223,Active,Normal Shop,2025-07-03 14:44:03.763814+05:30
482253,4612009,9,2024,731,732,1925.0,15157.0,0.0,0.0,0.0,...,0,982.0,Narayanpet,982012.0,Krishna,77.346762,16.413360,Active,Normal Shop,2025-07-03 14:44:03.763814+05:30
482254,4612010,9,2024,278,279,519.0,5730.0,0.0,0.0,0.0,...,0,982.0,Narayanpet,982012.0,Krishna,77.312684,16.477318,Active,Normal Shop,2025-07-03 14:44:03.763814+05:30
482255,4612011,9,2024,432,432,1015.0,8766.0,0.0,0.0,0.0,...,0,982.0,Narayanpet,982012.0,Krishna,77.317855,16.409945,Active,Normal Shop,2025-07-03 14:44:03.763814+05:30
482256,4612012,9,2024,201,202,70.0,4494.0,0.0,0.0,0.0,...,0,982.0,Narayanpet,982012.0,Krishna,77.283265,16.471927,Active,Normal Shop,2025-07-03 14:44:03.763814+05:30

In [44]:
#3. Full row missing check (important)
df.isnull().sum(axis=1).sort_values(ascending=False).head

<bound method NDFrame.head of 0         0
1         0
2         0
3         0
4         0
         ..
482252    0
482253    0
482254    0
482255    0
482256    0
Length: 482257, dtype: int64>

In [45]:
df[df.isnull().sum(axis=1) == 0].shape

(482257, 41)

In [46]:
dirty_rows = df[df.isnull().sum(axis=1) > 0]
dirty_rows.head()

Empty DataFrame
Columns: [shopNo, month, year, noOfRcs, noOfTrans, riceAfsc, riceFsc, riceAap, wheat, sugar, totalAmount, otherShopTransCnt, riceAap_available, wheat_available, rcNfsaAay, unitsNfsaAay, rcNfsaPhh, unitsNfsaPhh, totalRcNfsa, totalUnitsNfsa, rcStateAay, unitsStateAay, rcStatePhh, unitsStatePhh, rcStateAap, unitsStateAap, totalRcState, totalUnitsState, totalRcs, totalUnits, units, gasCylinders, distCode, distName, officeCode, officeName, longitude, latitude, fpsStatus, fpsType, dateTime]
Index: []

[0 rows x 41 columns]

In [47]:
df[df['latitude'].isnull()].head()

Empty DataFrame
Columns: [shopNo, month, year, noOfRcs, noOfTrans, riceAfsc, riceFsc, riceAap, wheat, sugar, totalAmount, otherShopTransCnt, riceAap_available, wheat_available, rcNfsaAay, unitsNfsaAay, rcNfsaPhh, unitsNfsaPhh, totalRcNfsa, totalUnitsNfsa, rcStateAay, unitsStateAay, rcStatePhh, unitsStatePhh, rcStateAap, unitsStateAap, totalRcState, totalUnitsState, totalRcs, totalUnits, units, gasCylinders, distCode, distName, officeCode, officeName, longitude, latitude, fpsStatus, fpsType, dateTime]
Index: []

[0 rows x 41 columns]

In [48]:
df['missing_count'] = df.isnull().sum(axis=1)

df[['missing_count']].value_counts()

missing_count
0                482257
Name: count, dtype: int64

In [49]:
print("Total rows:", len(df))
print("Fully clean rows:", df.dropna().shape[0])
print("Rows with missing:", df.isnull().any(axis=1).sum())

Total rows: 482257
Fully clean rows: 482257
Rows with missing: 0

In [50]:
df.shape

(482257, 42)

In [51]:
df.columns

Index(['shopNo', 'month', 'year', 'noOfRcs', 'noOfTrans', 'riceAfsc',
       'riceFsc', 'riceAap', 'wheat', 'sugar', 'totalAmount',
       'otherShopTransCnt', 'riceAap_available', 'wheat_available',
       'rcNfsaAay', 'unitsNfsaAay', 'rcNfsaPhh', 'unitsNfsaPhh', 'totalRcNfsa',
       'totalUnitsNfsa', 'rcStateAay', 'unitsStateAay', 'rcStatePhh',
       'unitsStatePhh', 'rcStateAap', 'unitsStateAap', 'totalRcState',
       'totalUnitsState', 'totalRcs', 'totalUnits', 'units', 'gasCylinders',
       'distCode', 'distName', 'officeCode', 'officeName', 'longitude',
       'latitude', 'fpsStatus', 'fpsType', 'dateTime', 'missing_count'],
      dtype='object')

In [52]:
df.duplicated(subset=['shopNo', 'month', 'year']).sum()

np.int64(0)

In [53]:
df.drop(columns=['missing_count'], inplace=True)

In [57]:
df.to_csv("../data/Master_data/Cleanning_and_preprosscing.csv", index=False)

print("Save clean_data")

Save clean_data

In [55]:
df.shape

(482257, 41)

In [56]:
df.columns

Index(['shopNo', 'month', 'year', 'noOfRcs', 'noOfTrans', 'riceAfsc',
       'riceFsc', 'riceAap', 'wheat', 'sugar', 'totalAmount',
       'otherShopTransCnt', 'riceAap_available', 'wheat_available',
       'rcNfsaAay', 'unitsNfsaAay', 'rcNfsaPhh', 'unitsNfsaPhh', 'totalRcNfsa',
       'totalUnitsNfsa', 'rcStateAay', 'unitsStateAay', 'rcStatePhh',
       'unitsStatePhh', 'rcStateAap', 'unitsStateAap', 'totalRcState',
       'totalUnitsState', 'totalRcs', 'totalUnits', 'units', 'gasCylinders',
       'distCode', 'distName', 'officeCode', 'officeName', 'longitude',
       'latitude', 'fpsStatus', 'fpsType', 'dateTime'],
      dtype='object')