In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('../data/Master_data/outlier_cliping_dataset.csv')

In [4]:
df.shape

(482257, 26)

In [5]:
df.columns

Index(['shopNo', 'month', 'year', 'noOfRcs', 'noOfTrans', 'riceAfsc',
       'riceFsc', 'riceAap', 'wheat', 'sugar', 'totalAmount',
       'otherShopTransCnt', 'riceAap_available', 'wheat_available', 'totalRcs',
       'totalUnits', 'units', 'distCode', 'distName', 'officeCode',
       'officeName', 'longitude', 'latitude', 'fpsStatus', 'fpsType',
       'dateTime'],
      dtype='object')

In [6]:
# check Numeric or Categorical coloumns
print(df.select_dtypes(include='object').columns)
numeric_cols = df.select_dtypes(include=np.number).columns

print(numeric_cols)

Index(['distName', 'officeName', 'fpsStatus', 'fpsType', 'dateTime'], dtype='object')
Index(['shopNo', 'month', 'year', 'noOfRcs', 'noOfTrans', 'riceAfsc',
       'riceFsc', 'riceAap', 'wheat', 'sugar', 'totalAmount',
       'otherShopTransCnt', 'riceAap_available', 'wheat_available', 'totalRcs',
       'totalUnits', 'units', 'distCode', 'officeCode', 'longitude',
       'latitude'],
      dtype='object')

In [7]:
# DATE & TIME FEATURES
df['dateTime'] = pd.to_datetime(df['dateTime'])

df['day_name'] = df['dateTime'].dt.day_name()
df['week'] = df['dateTime'].dt.isocalendar().week
df['quarter'] = df['dateTime'].dt.quarter
df['is_weekend'] = (df['dateTime'].dt.weekday >= 5).astype(int)
df['day_of_year'] = df['dateTime'].dt.dayofyear
df['month_start'] = df['dateTime'].dt.is_month_start.astype(int)
df['month_end'] = df['dateTime'].dt.is_month_end.astype(int)
df['days_in_month'] = df['dateTime'].dt.days_in_month

In [8]:
#BASIC UTILIZATION FEATURES

# Transactions per ration card
df['utilization_ratio'] = (
    df['noOfTrans'] /
    (df['totalRcs'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,dateTime,day_name,week,quarter,is_weekend,day_of_year,month_start,month_end,days_in_month,utilization_ratio
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,2025-07-03 14:43:54.124224+05:30,Thursday,27,3,0,184,0,0,31,0.898893
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,2025-07-03 14:43:54.124224+05:30,Thursday,27,3,0,184,0,0,31,0.892308
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,2025-07-03 14:43:54.124224+05:30,Thursday,27,3,0,184,0,0,31,0.907850
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,2025-07-03 14:43:54.124224+05:30,Thursday,27,3,0,184,0,0,31,0.908867
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,2025-07-03 14:43:54.124224+05:30,Thursday,27,3,0,184,0,0,31,0.941298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,2025-07-03 14:44:03.763814+05:30,Thursday,27,3,0,184,0,0,31,0.812339
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,2025-07-03 14:44:03.763814+05:30,Thursday,27,3,0,184,0,0,31,0.851163
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,2025-07-03 14:44:03.763814+05:30,Thursday,27,3,0,184,0,0,31,0.656471
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,2025-07-03 14:44:03.763814+05:30,Thursday,27,3,0,184,0,0,31,0.586160
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,2025-07-03 14:44:03.763814+05:30,Thursday,27,3,0,184,0,0,31,0.677852

In [9]:
# Units distributed per ration card
df['units_per_card'] = (
    df['totalUnits'] /
    (df['totalRcs'] + 1)
 )
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,day_name,week,quarter,is_weekend,day_of_year,month_start,month_end,days_in_month,utilization_ratio,units_per_card
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,Thursday,27,3,0,184,0,0,31,0.898893,3.125662
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,Thursday,27,3,0,184,0,0,31,0.892308,3.208547
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,Thursday,27,3,0,184,0,0,31,0.907850,3.249147
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,Thursday,27,3,0,184,0,0,31,0.908867,3.320197
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,Thursday,27,3,0,184,0,0,31,0.941298,3.342945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,Thursday,27,3,0,184,0,0,31,0.812339,3.596401
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,Thursday,27,3,0,184,0,0,31,0.851163,3.532558
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,Thursday,27,3,0,184,0,0,31,0.656471,3.192941
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,Thursday,27,3,0,184,0,0,31,0.586160,3.312076
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,Thursday,27,3,0,184,0,0,31,0.677852,3.506711

In [10]:
# Average transaction amount
df['amount_per_transaction'] = (
    df['totalAmount'] /
    (df['noOfTrans'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,week,quarter,is_weekend,day_of_year,month_start,month_end,days_in_month,utilization_ratio,units_per_card,amount_per_transaction
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,27,3,0,184,0,0,31,0.898893,3.125662,0.0
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,27,3,0,184,0,0,31,0.892308,3.208547,0.0
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,27,3,0,184,0,0,31,0.907850,3.249147,0.0
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,27,3,0,184,0,0,31,0.908867,3.320197,0.0
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,27,3,0,184,0,0,31,0.941298,3.342945,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,27,3,0,184,0,0,31,0.812339,3.596401,0.0
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,27,3,0,184,0,0,31,0.851163,3.532558,0.0
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,27,3,0,184,0,0,31,0.656471,3.192941,0.0
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,27,3,0,184,0,0,31,0.586160,3.312076,0.0
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,27,3,0,184,0,0,31,0.677852,3.506711,0.0

In [11]:
# Average transaction value per card
df['amount_per_card'] = (
    df['totalAmount'] /
    (df['totalRcs'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,quarter,is_weekend,day_of_year,month_start,month_end,days_in_month,utilization_ratio,units_per_card,amount_per_transaction,amount_per_card
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,3,0,184,0,0,31,0.898893,3.125662,0.0,0.0
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,3,0,184,0,0,31,0.892308,3.208547,0.0,0.0
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,3,0,184,0,0,31,0.907850,3.249147,0.0,0.0
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,3,0,184,0,0,31,0.908867,3.320197,0.0,0.0
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,3,0,184,0,0,31,0.941298,3.342945,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,3,0,184,0,0,31,0.812339,3.596401,0.0,0.0
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,3,0,184,0,0,31,0.851163,3.532558,0.0,0.0
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,3,0,184,0,0,31,0.656471,3.192941,0.0,0.0
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,3,0,184,0,0,31,0.586160,3.312076,0.0,0.0
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,3,0,184,0,0,31,0.677852,3.506711,0.0,0.0

In [12]:
# COMMODITY FEATURES

# Commodity per transaction
df['rice_afsc_per_trans'] = (
    df['riceAfsc'] /
    (df['noOfTrans'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,is_weekend,day_of_year,month_start,month_end,days_in_month,utilization_ratio,units_per_card,amount_per_transaction,amount_per_card,rice_afsc_per_trans
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,0,184,0,0,31,0.898893,3.125662,0.0,0.0,1.460674
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,0,184,0,0,31,0.892308,3.208547,0.0,0.0,1.338432
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,0,184,0,0,31,0.907850,3.249147,0.0,0.0,2.228464
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,0,184,0,0,31,0.908867,3.320197,0.0,0.0,1.324324
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,0,184,0,0,31,0.941298,3.342945,0.0,0.0,2.658470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,0,184,0,0,31,0.812339,3.596401,0.0,0.0,2.429022
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,0,184,0,0,31,0.851163,3.532558,0.0,0.0,2.626194
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,0,184,0,0,31,0.656471,3.192941,0.0,0.0,1.853571
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,0,184,0,0,31,0.586160,3.312076,0.0,0.0,2.344111
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0,184,0,0,31,0.677852,3.506711,0.0,0.0,0.344828

In [13]:
df['rice_fsc_per_trans'] = (
    df['riceFsc'] /
    (df['noOfTrans'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,day_of_year,month_start,month_end,days_in_month,utilization_ratio,units_per_card,amount_per_transaction,amount_per_card,rice_afsc_per_trans,rice_fsc_per_trans
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,184,0,0,31,0.898893,3.125662,0.0,0.0,1.460674,17.995185
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,184,0,0,31,0.892308,3.208547,0.0,0.0,1.338432,18.734226
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,184,0,0,31,0.907850,3.249147,0.0,0.0,2.228464,18.247191
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,184,0,0,31,0.908867,3.320197,0.0,0.0,1.324324,19.564865
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,184,0,0,31,0.941298,3.342945,0.0,0.0,2.658470,17.593443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,184,0,0,31,0.812339,3.596401,0.0,0.0,2.429022,21.577287
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,184,0,0,31,0.851163,3.532558,0.0,0.0,2.626194,20.678035
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,184,0,0,31,0.656471,3.192941,0.0,0.0,1.853571,20.464286
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,184,0,0,31,0.586160,3.312076,0.0,0.0,2.344111,20.244804
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,184,0,0,31,0.677852,3.506711,0.0,0.0,0.344828,22.137931

In [14]:
df['rice_aap_per_trans'] = (
    df['riceAap'] /
    (df['noOfTrans'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,month_start,month_end,days_in_month,utilization_ratio,units_per_card,amount_per_transaction,amount_per_card,rice_afsc_per_trans,rice_fsc_per_trans,rice_aap_per_trans
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,0,0,31,0.898893,3.125662,0.0,0.0,1.460674,17.995185,0.000000
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,0,0,31,0.892308,3.208547,0.0,0.0,1.338432,18.734226,0.000000
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,0,0,31,0.907850,3.249147,0.0,0.0,2.228464,18.247191,0.000000
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,0,0,31,0.908867,3.320197,0.0,0.0,1.324324,19.564865,0.027027
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,0,0,31,0.941298,3.342945,0.0,0.0,2.658470,17.593443,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,0,0,31,0.812339,3.596401,0.0,0.0,2.429022,21.577287,0.000000
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,0,0,31,0.851163,3.532558,0.0,0.0,2.626194,20.678035,0.000000
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,0,0,31,0.656471,3.192941,0.0,0.0,1.853571,20.464286,0.000000
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,0,0,31,0.586160,3.312076,0.0,0.0,2.344111,20.244804,0.000000
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0,0,31,0.677852,3.506711,0.0,0.0,0.344828,22.137931,0.000000

In [15]:
df['wheat_per_trans'] = (
    df['wheat'] /
    (df['noOfTrans'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,month_end,days_in_month,utilization_ratio,units_per_card,amount_per_transaction,amount_per_card,rice_afsc_per_trans,rice_fsc_per_trans,rice_aap_per_trans,wheat_per_trans
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,0,31,0.898893,3.125662,0.0,0.0,1.460674,17.995185,0.000000,0.0
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,0,31,0.892308,3.208547,0.0,0.0,1.338432,18.734226,0.000000,0.0
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,0,31,0.907850,3.249147,0.0,0.0,2.228464,18.247191,0.000000,0.0
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,0,31,0.908867,3.320197,0.0,0.0,1.324324,19.564865,0.027027,0.0
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,0,31,0.941298,3.342945,0.0,0.0,2.658470,17.593443,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,0,31,0.812339,3.596401,0.0,0.0,2.429022,21.577287,0.000000,0.0
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,0,31,0.851163,3.532558,0.0,0.0,2.626194,20.678035,0.000000,0.0
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,0,31,0.656471,3.192941,0.0,0.0,1.853571,20.464286,0.000000,0.0
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,0,31,0.586160,3.312076,0.0,0.0,2.344111,20.244804,0.000000,0.0
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0,31,0.677852,3.506711,0.0,0.0,0.344828,22.137931,0.000000,0.0

In [16]:
# COMMODITY INTENSITY FEATURES
# Rice-to-Wheat Ratio
df['rice_to_wheat_ratio'] = (
    (df['riceAfsc'] + df['riceFsc'] + df['riceAap']) /
    (df['wheat'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,days_in_month,utilization_ratio,units_per_card,amount_per_transaction,amount_per_card,rice_afsc_per_trans,rice_fsc_per_trans,rice_aap_per_trans,wheat_per_trans,rice_to_wheat_ratio
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,31,0.898893,3.125662,0.0,0.0,1.460674,17.995185,0.000000,0.0,18181.5
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,31,0.892308,3.208547,0.0,0.0,1.338432,18.734226,0.000000,0.0,10498.0
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,31,0.907850,3.249147,0.0,0.0,2.228464,18.247191,0.000000,0.0,5467.0
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,31,0.908867,3.320197,0.0,0.0,1.324324,19.564865,0.027027,0.0,7739.0
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,31,0.941298,3.342945,0.0,0.0,2.658470,17.593443,0.000000,0.0,18530.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,31,0.812339,3.596401,0.0,0.0,2.429022,21.577287,0.000000,0.0,7610.0
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,31,0.851163,3.532558,0.0,0.0,2.626194,20.678035,0.000000,0.0,17082.0
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,31,0.656471,3.192941,0.0,0.0,1.853571,20.464286,0.000000,0.0,6249.0
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,31,0.586160,3.312076,0.0,0.0,2.344111,20.244804,0.000000,0.0,9781.0
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,31,0.677852,3.506711,0.0,0.0,0.344828,22.137931,0.000000,0.0,4564.0

In [17]:
# Sugar Intensity
df['sugar_intensity'] = (
    df['sugar'] /
    (df['totalUnits'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,utilization_ratio,units_per_card,amount_per_transaction,amount_per_card,rice_afsc_per_trans,rice_fsc_per_trans,rice_aap_per_trans,wheat_per_trans,rice_to_wheat_ratio,sugar_intensity
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,0.898893,3.125662,0.0,0.0,1.460674,17.995185,0.000000,0.0,18181.5,0.0
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,0.892308,3.208547,0.0,0.0,1.338432,18.734226,0.000000,0.0,10498.0,0.0
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,0.907850,3.249147,0.0,0.0,2.228464,18.247191,0.000000,0.0,5467.0,0.0
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,0.908867,3.320197,0.0,0.0,1.324324,19.564865,0.027027,0.0,7739.0,0.0
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,0.941298,3.342945,0.0,0.0,2.658470,17.593443,0.000000,0.0,18530.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,0.812339,3.596401,0.0,0.0,2.429022,21.577287,0.000000,0.0,7610.0,0.0
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,0.851163,3.532558,0.0,0.0,2.626194,20.678035,0.000000,0.0,17082.0,0.0
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,0.656471,3.192941,0.0,0.0,1.853571,20.464286,0.000000,0.0,6249.0,0.0
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,0.586160,3.312076,0.0,0.0,2.344111,20.244804,0.000000,0.0,9781.0,0.0
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0.677852,3.506711,0.0,0.0,0.344828,22.137931,0.000000,0.0,4564.0,0.0

In [18]:
# Wheat Intensity
df['wheat_intensity'] = (
    df['wheat'] /
    (df['totalUnits'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,units_per_card,amount_per_transaction,amount_per_card,rice_afsc_per_trans,rice_fsc_per_trans,rice_aap_per_trans,wheat_per_trans,rice_to_wheat_ratio,sugar_intensity,wheat_intensity
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,3.125662,0.0,0.0,1.460674,17.995185,0.000000,0.0,18181.5,0.0,0.0
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,3.208547,0.0,0.0,1.338432,18.734226,0.000000,0.0,10498.0,0.0,0.0
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,3.249147,0.0,0.0,2.228464,18.247191,0.000000,0.0,5467.0,0.0,0.0
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,3.320197,0.0,0.0,1.324324,19.564865,0.027027,0.0,7739.0,0.0,0.0
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,3.342945,0.0,0.0,2.658470,17.593443,0.000000,0.0,18530.5,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,3.596401,0.0,0.0,2.429022,21.577287,0.000000,0.0,7610.0,0.0,0.0
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,3.532558,0.0,0.0,2.626194,20.678035,0.000000,0.0,17082.0,0.0,0.0
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,3.192941,0.0,0.0,1.853571,20.464286,0.000000,0.0,6249.0,0.0,0.0
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,3.312076,0.0,0.0,2.344111,20.244804,0.000000,0.0,9781.0,0.0,0.0
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,3.506711,0.0,0.0,0.344828,22.137931,0.000000,0.0,4564.0,0.0,0.0

In [19]:
# Rice Share
df['rice_share'] = (
    (df['riceAfsc'] + df['riceFsc'] + df['riceAap']) /
    (df['totalUnits'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,amount_per_transaction,amount_per_card,rice_afsc_per_trans,rice_fsc_per_trans,rice_aap_per_trans,wheat_per_trans,rice_to_wheat_ratio,sugar_intensity,wheat_intensity,rice_share
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,0.0,0.0,1.460674,17.995185,0.000000,0.0,18181.5,0.0,0.0,5.599476
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,0.0,0.0,1.338432,18.734226,0.000000,0.0,10498.0,0.0,0.0,5.589989
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,0.0,0.0,2.228464,18.247191,0.000000,0.0,5467.0,0.0,0.0,5.736621
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,0.0,0.0,1.324324,19.564865,0.027027,0.0,7739.0,0.0,0.0,5.736842
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,0.0,0.0,2.658470,17.593443,0.000000,0.0,18530.5,0.0,0.0,5.706960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,0.0,0.0,2.429022,21.577287,0.000000,0.0,7610.0,0.0,0.0,5.435714
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,0.0,0.0,2.626194,20.678035,0.000000,0.0,17082.0,0.0,0.0,5.620928
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,0.0,0.0,1.853571,20.464286,0.000000,0.0,6249.0,0.0,0.0,4.601620
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,0.0,0.0,2.344111,20.244804,0.000000,0.0,9781.0,0.0,0.0,4.005324
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0.0,0.0,0.344828,22.137931,0.000000,0.0,4564.0,0.0,0.0,4.363289

In [20]:
# Total Commodity Activity
df['commodity_activity'] = (
    (df['riceAfsc'] > 0).astype(int) +
    (df['riceFsc'] > 0).astype(int) +
    (df['riceAap'] > 0).astype(int) +
    (df['wheat'] > 0).astype(int) +
    (df['sugar'] > 0).astype(int)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,amount_per_card,rice_afsc_per_trans,rice_fsc_per_trans,rice_aap_per_trans,wheat_per_trans,rice_to_wheat_ratio,sugar_intensity,wheat_intensity,rice_share,commodity_activity
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,0.0,1.460674,17.995185,0.000000,0.0,18181.5,0.0,0.0,5.599476,2
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,0.0,1.338432,18.734226,0.000000,0.0,10498.0,0.0,0.0,5.589989,2
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,0.0,2.228464,18.247191,0.000000,0.0,5467.0,0.0,0.0,5.736621,2
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,0.0,1.324324,19.564865,0.027027,0.0,7739.0,0.0,0.0,5.736842,3
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,0.0,2.658470,17.593443,0.000000,0.0,18530.5,0.0,0.0,5.706960,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,0.0,2.429022,21.577287,0.000000,0.0,7610.0,0.0,0.0,5.435714,2
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,0.0,2.626194,20.678035,0.000000,0.0,17082.0,0.0,0.0,5.620928,2
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,0.0,1.853571,20.464286,0.000000,0.0,6249.0,0.0,0.0,4.601620,2
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,0.0,2.344111,20.244804,0.000000,0.0,9781.0,0.0,0.0,4.005324,2
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0.0,0.344828,22.137931,0.000000,0.0,4564.0,0.0,0.0,4.363289,2

In [21]:
# PORTABILITY FEATURES
# Other shop dependency
df['other_shop_ratio'] = (
    df['otherShopTransCnt'] /
    (df['noOfTrans'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,rice_afsc_per_trans,rice_fsc_per_trans,rice_aap_per_trans,wheat_per_trans,rice_to_wheat_ratio,sugar_intensity,wheat_intensity,rice_share,commodity_activity,other_shop_ratio
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,1.460674,17.995185,0.000000,0.0,18181.5,0.0,0.0,5.599476,2,0.037453
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,1.338432,18.734226,0.000000,0.0,10498.0,0.0,0.0,5.589989,2,0.045889
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,2.228464,18.247191,0.000000,0.0,5467.0,0.0,0.0,5.736621,2,0.067416
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,1.324324,19.564865,0.027027,0.0,7739.0,0.0,0.0,5.736842,3,0.051351
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,2.658470,17.593443,0.000000,0.0,18530.5,0.0,0.0,5.706960,2,0.036066
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,2.429022,21.577287,0.000000,0.0,7610.0,0.0,0.0,5.435714,2,0.034700
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,2.626194,20.678035,0.000000,0.0,17082.0,0.0,0.0,5.620928,2,0.132333
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,1.853571,20.464286,0.000000,0.0,6249.0,0.0,0.0,4.601620,2,0.025000
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,2.344111,20.244804,0.000000,0.0,9781.0,0.0,0.0,4.005324,2,0.034642
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0.344828,22.137931,0.000000,0.0,4564.0,0.0,0.0,4.363289,2,0.044335

In [22]:
# Portability hub score
df['portability_hub_score'] = (
    df['otherShopTransCnt'] *
    df['utilization_ratio']
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,rice_fsc_per_trans,rice_aap_per_trans,wheat_per_trans,rice_to_wheat_ratio,sugar_intensity,wheat_intensity,rice_share,commodity_activity,other_shop_ratio,portability_hub_score
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,17.995185,0.000000,0.0,18181.5,0.0,0.0,5.599476,2,0.037453,31.461242
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,18.734226,0.000000,0.0,10498.0,0.0,0.0,5.589989,2,0.045889,21.415385
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,18.247191,0.000000,0.0,5467.0,0.0,0.0,5.736621,2,0.067416,16.341297
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,19.564865,0.027027,0.0,7739.0,0.0,0.0,5.736842,3,0.051351,17.268473
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,17.593443,0.000000,0.0,18530.5,0.0,0.0,5.706960,2,0.036066,31.062822
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,21.577287,0.000000,0.0,7610.0,0.0,0.0,5.435714,2,0.034700,8.935733
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,20.678035,0.000000,0.0,17082.0,0.0,0.0,5.620928,2,0.132333,82.562791
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,20.464286,0.000000,0.0,6249.0,0.0,0.0,4.601620,2,0.025000,4.595294
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,20.244804,0.000000,0.0,9781.0,0.0,0.0,4.005324,2,0.034642,8.792402
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,22.137931,0.000000,0.0,4564.0,0.0,0.0,4.363289,2,0.044335,6.100671

In [23]:
# Portability intensity
df['portability_intensity'] = (
    df['otherShopTransCnt'] /
    (df['totalRcs'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,rice_aap_per_trans,wheat_per_trans,rice_to_wheat_ratio,sugar_intensity,wheat_intensity,rice_share,commodity_activity,other_shop_ratio,portability_hub_score,portability_intensity
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,0.000000,0.0,18181.5,0.0,0.0,5.599476,2,0.037453,31.461242,0.033702
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,0.000000,0.0,10498.0,0.0,0.0,5.589989,2,0.045889,21.415385,0.041026
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,0.000000,0.0,5467.0,0.0,0.0,5.736621,2,0.067416,16.341297,0.061433
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,0.027027,0.0,7739.0,0.0,0.0,5.736842,3,0.051351,17.268473,0.046798
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,0.000000,0.0,18530.5,0.0,0.0,5.706960,2,0.036066,31.062822,0.033986
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,0.000000,0.0,7610.0,0.0,0.0,5.435714,2,0.034700,8.935733,0.028278
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,0.000000,0.0,17082.0,0.0,0.0,5.620928,2,0.132333,82.562791,0.112791
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,0.000000,0.0,6249.0,0.0,0.0,4.601620,2,0.025000,4.595294,0.016471
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,0.000000,0.0,9781.0,0.0,0.0,4.005324,2,0.034642,8.792402,0.020353
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0.000000,0.0,4564.0,0.0,0.0,4.363289,2,0.044335,6.100671,0.030201

In [24]:
# High non-local traffic shops
df['high_non_local_flag'] = (
    df['other_shop_ratio'] >
    df['other_shop_ratio'].quantile(0.90)
).astype(int)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,wheat_per_trans,rice_to_wheat_ratio,sugar_intensity,wheat_intensity,rice_share,commodity_activity,other_shop_ratio,portability_hub_score,portability_intensity,high_non_local_flag
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,0.0,18181.5,0.0,0.0,5.599476,2,0.037453,31.461242,0.033702,0
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,0.0,10498.0,0.0,0.0,5.589989,2,0.045889,21.415385,0.041026,0
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,0.0,5467.0,0.0,0.0,5.736621,2,0.067416,16.341297,0.061433,0
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,0.0,7739.0,0.0,0.0,5.736842,3,0.051351,17.268473,0.046798,0
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,0.0,18530.5,0.0,0.0,5.706960,2,0.036066,31.062822,0.033986,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,0.0,7610.0,0.0,0.0,5.435714,2,0.034700,8.935733,0.028278,0
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,0.0,17082.0,0.0,0.0,5.620928,2,0.132333,82.562791,0.112791,0
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,0.0,6249.0,0.0,0.0,4.601620,2,0.025000,4.595294,0.016471,0
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,0.0,9781.0,0.0,0.0,4.005324,2,0.034642,8.792402,0.020353,0
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0.0,4564.0,0.0,0.0,4.363289,2,0.044335,6.100671,0.030201,0

In [26]:
#FRAUD DETECTION FEATURES
# Transactions per card
df['trans_per_card_FRAUD_DETECTION'] = (
    df['noOfTrans'] /
    (df['totalRcs'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,rice_to_wheat_ratio,sugar_intensity,wheat_intensity,rice_share,commodity_activity,other_shop_ratio,portability_hub_score,portability_intensity,high_non_local_flag,trans_per_card_FRAUD_DETECTION
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,18181.5,0.0,0.0,5.599476,2,0.037453,31.461242,0.033702,0,0.898893
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,10498.0,0.0,0.0,5.589989,2,0.045889,21.415385,0.041026,0,0.892308
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,5467.0,0.0,0.0,5.736621,2,0.067416,16.341297,0.061433,0,0.907850
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,7739.0,0.0,0.0,5.736842,3,0.051351,17.268473,0.046798,0,0.908867
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,18530.5,0.0,0.0,5.706960,2,0.036066,31.062822,0.033986,0,0.941298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,7610.0,0.0,0.0,5.435714,2,0.034700,8.935733,0.028278,0,0.812339
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,17082.0,0.0,0.0,5.620928,2,0.132333,82.562791,0.112791,0,0.851163
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,6249.0,0.0,0.0,4.601620,2,0.025000,4.595294,0.016471,0,0.656471
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,9781.0,0.0,0.0,4.005324,2,0.034642,8.792402,0.020353,0,0.586160
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,4564.0,0.0,0.0,4.363289,2,0.044335,6.100671,0.030201,0,0.677852

In [27]:
# Units per transaction
df['units_per_trans_FRAUD_DETECTION'] = (
    df['totalUnits'] /
    (df['noOfTrans'] + 1)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,sugar_intensity,wheat_intensity,rice_share,commodity_activity,other_shop_ratio,portability_hub_score,portability_intensity,high_non_local_flag,trans_per_card_FRAUD_DETECTION,units_per_trans_FRAUD_DETECTION
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,0.0,0.0,5.599476,2,0.037453,31.461242,0.033702,0,0.898893,3.473515
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,0.0,0.0,5.589989,2,0.045889,21.415385,0.041026,0,0.892308,3.588910
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,0.0,0.0,5.736621,2,0.067416,16.341297,0.061433,0,0.907850,3.565543
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,0.0,0.0,5.736842,3,0.051351,17.268473,0.046798,0,0.908867,3.643243
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,0.0,0.0,5.706960,2,0.036066,31.062822,0.033986,0,0.941298,3.547541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,0.0,0.0,5.435714,2,0.034700,8.935733,0.028278,0,0.812339,4.413249
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,0.0,0.0,5.620928,2,0.132333,82.562791,0.112791,0,0.851163,4.144611
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,0.0,0.0,4.601620,2,0.025000,4.595294,0.016471,0,0.656471,4.846429
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,0.0,0.0,4.005324,2,0.034642,8.792402,0.020353,0,0.586160,5.637413
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0.0,0.0,4.363289,2,0.044335,6.100671,0.030201,0,0.677852,5.147783

In [28]:
print(df.columns)

Index(['shopNo', 'month', 'year', 'noOfRcs', 'noOfTrans', 'riceAfsc',
       'riceFsc', 'riceAap', 'wheat', 'sugar', 'totalAmount',
       'otherShopTransCnt', 'riceAap_available', 'wheat_available', 'totalRcs',
       'totalUnits', 'units', 'distCode', 'distName', 'officeCode',
       'officeName', 'longitude', 'latitude', 'fpsStatus', 'fpsType',
       'dateTime', 'day_name', 'week', 'quarter', 'is_weekend', 'day_of_year',
       'month_start', 'month_end', 'days_in_month', 'utilization_ratio',
       'units_per_card', 'amount_per_transaction', 'amount_per_card',
       'rice_afsc_per_trans', 'rice_fsc_per_trans', 'rice_aap_per_trans',
       'wheat_per_trans', 'rice_to_wheat_ratio', 'sugar_intensity',
       'wheat_intensity', 'rice_share', 'commodity_activity',
       'other_shop_ratio', 'portability_hub_score', 'portability_intensity',
       'high_non_local_flag', 'trans_per_card_FRAUD_DETECTION',
       'units_per_trans_FRAUD_DETECTION'],
      dtype='object')

In [29]:
# Fraud risk threshold
fraud_threshold = (
    df['trans_per_card_FRAUD_DETECTION']
    .quantile(0.99)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,sugar_intensity,wheat_intensity,rice_share,commodity_activity,other_shop_ratio,portability_hub_score,portability_intensity,high_non_local_flag,trans_per_card_FRAUD_DETECTION,units_per_trans_FRAUD_DETECTION
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,0.0,0.0,5.599476,2,0.037453,31.461242,0.033702,0,0.898893,3.473515
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,0.0,0.0,5.589989,2,0.045889,21.415385,0.041026,0,0.892308,3.588910
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,0.0,0.0,5.736621,2,0.067416,16.341297,0.061433,0,0.907850,3.565543
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,0.0,0.0,5.736842,3,0.051351,17.268473,0.046798,0,0.908867,3.643243
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,0.0,0.0,5.706960,2,0.036066,31.062822,0.033986,0,0.941298,3.547541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,0.0,0.0,5.435714,2,0.034700,8.935733,0.028278,0,0.812339,4.413249
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,0.0,0.0,5.620928,2,0.132333,82.562791,0.112791,0,0.851163,4.144611
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,0.0,0.0,4.601620,2,0.025000,4.595294,0.016471,0,0.656471,4.846429
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,0.0,0.0,4.005324,2,0.034642,8.792402,0.020353,0,0.586160,5.637413
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0.0,0.0,4.363289,2,0.044335,6.100671,0.030201,0,0.677852,5.147783

In [30]:
# Fraud risk flag
df['fraud_risk_flag'] = (
    df['trans_per_card_FRAUD_DETECTION'] >
    fraud_threshold
).astype(int)

df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,wheat_intensity,rice_share,commodity_activity,other_shop_ratio,portability_hub_score,portability_intensity,high_non_local_flag,trans_per_card_FRAUD_DETECTION,units_per_trans_FRAUD_DETECTION,fraud_risk_flag
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,0.0,5.599476,2,0.037453,31.461242,0.033702,0,0.898893,3.473515,0
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,0.0,5.589989,2,0.045889,21.415385,0.041026,0,0.892308,3.588910,0
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,0.0,5.736621,2,0.067416,16.341297,0.061433,0,0.907850,3.565543,0
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,0.0,5.736842,3,0.051351,17.268473,0.046798,0,0.908867,3.643243,0
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,0.0,5.706960,2,0.036066,31.062822,0.033986,0,0.941298,3.547541,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,0.0,5.435714,2,0.034700,8.935733,0.028278,0,0.812339,4.413249,0
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,0.0,5.620928,2,0.132333,82.562791,0.112791,0,0.851163,4.144611,0
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,0.0,4.601620,2,0.025000,4.595294,0.016471,0,0.656471,4.846429,0
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,0.0,4.005324,2,0.034642,8.792402,0.020353,0,0.586160,5.637413,0
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0.0,4.363289,2,0.044335,6.100671,0.030201,0,0.677852,5.147783,0

In [31]:
# POLICY IMPACT FEATURES
# ONORC implementation indicator
df['post_onorc'] = (
    df['year'] >= 2020
).astype(int)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,rice_share,commodity_activity,other_shop_ratio,portability_hub_score,portability_intensity,high_non_local_flag,trans_per_card_FRAUD_DETECTION,units_per_trans_FRAUD_DETECTION,fraud_risk_flag,post_onorc
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,5.599476,2,0.037453,31.461242,0.033702,0,0.898893,3.473515,0,1
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,5.589989,2,0.045889,21.415385,0.041026,0,0.892308,3.588910,0,1
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,5.736621,2,0.067416,16.341297,0.061433,0,0.907850,3.565543,0,1
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,5.736842,3,0.051351,17.268473,0.046798,0,0.908867,3.643243,0,1
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,5.706960,2,0.036066,31.062822,0.033986,0,0.941298,3.547541,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,5.435714,2,0.034700,8.935733,0.028278,0,0.812339,4.413249,0,1
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,5.620928,2,0.132333,82.562791,0.112791,0,0.851163,4.144611,0,1
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,4.601620,2,0.025000,4.595294,0.016471,0,0.656471,4.846429,0,1
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,4.005324,2,0.034642,8.792402,0.020353,0,0.586160,5.637413,0,1
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,4.363289,2,0.044335,6.100671,0.030201,0,0.677852,5.147783,0,1

In [32]:
# Urban/Rural Proxy
office_counts = (
    df.groupby('distCode')['officeCode']
    .transform('count')
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,rice_share,commodity_activity,other_shop_ratio,portability_hub_score,portability_intensity,high_non_local_flag,trans_per_card_FRAUD_DETECTION,units_per_trans_FRAUD_DETECTION,fraud_risk_flag,post_onorc
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,5.599476,2,0.037453,31.461242,0.033702,0,0.898893,3.473515,0,1
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,5.589989,2,0.045889,21.415385,0.041026,0,0.892308,3.588910,0,1
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,5.736621,2,0.067416,16.341297,0.061433,0,0.907850,3.565543,0,1
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,5.736842,3,0.051351,17.268473,0.046798,0,0.908867,3.643243,0,1
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,5.706960,2,0.036066,31.062822,0.033986,0,0.941298,3.547541,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,5.435714,2,0.034700,8.935733,0.028278,0,0.812339,4.413249,0,1
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,5.620928,2,0.132333,82.562791,0.112791,0,0.851163,4.144611,0,1
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,4.601620,2,0.025000,4.595294,0.016471,0,0.656471,4.846429,0,1
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,4.005324,2,0.034642,8.792402,0.020353,0,0.586160,5.637413,0,1
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,4.363289,2,0.044335,6.100671,0.030201,0,0.677852,5.147783,0,1

In [33]:
df['urban_proxy'] = (
    office_counts >
    office_counts.median()
).astype(int)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,commodity_activity,other_shop_ratio,portability_hub_score,portability_intensity,high_non_local_flag,trans_per_card_FRAUD_DETECTION,units_per_trans_FRAUD_DETECTION,fraud_risk_flag,post_onorc,urban_proxy
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,2,0.037453,31.461242,0.033702,0,0.898893,3.473515,0,1,0
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,2,0.045889,21.415385,0.041026,0,0.892308,3.588910,0,1,0
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,2,0.067416,16.341297,0.061433,0,0.907850,3.565543,0,1,0
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,3,0.051351,17.268473,0.046798,0,0.908867,3.643243,0,1,0
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,2,0.036066,31.062822,0.033986,0,0.941298,3.547541,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,2,0.034700,8.935733,0.028278,0,0.812339,4.413249,0,1,0
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,2,0.132333,82.562791,0.112791,0,0.851163,4.144611,0,1,0
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,2,0.025000,4.595294,0.016471,0,0.656471,4.846429,0,1,0
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,2,0.034642,8.792402,0.020353,0,0.586160,5.637413,0,1,0
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,2,0.044335,6.100671,0.030201,0,0.677852,5.147783,0,1,0

In [34]:
# Policy impact feature
df['distribution_change'] = (
    df['post_onorc'] *
    df['other_shop_ratio']
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,other_shop_ratio,portability_hub_score,portability_intensity,high_non_local_flag,trans_per_card_FRAUD_DETECTION,units_per_trans_FRAUD_DETECTION,fraud_risk_flag,post_onorc,urban_proxy,distribution_change
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,0.037453,31.461242,0.033702,0,0.898893,3.473515,0,1,0,0.037453
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,0.045889,21.415385,0.041026,0,0.892308,3.588910,0,1,0,0.045889
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,0.067416,16.341297,0.061433,0,0.907850,3.565543,0,1,0,0.067416
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,0.051351,17.268473,0.046798,0,0.908867,3.643243,0,1,0,0.051351
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,0.036066,31.062822,0.033986,0,0.941298,3.547541,0,1,0,0.036066
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,0.034700,8.935733,0.028278,0,0.812339,4.413249,0,1,0,0.034700
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,0.132333,82.562791,0.112791,0,0.851163,4.144611,0,1,0,0.132333
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,0.025000,4.595294,0.016471,0,0.656471,4.846429,0,1,0,0.025000
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,0.034642,8.792402,0.020353,0,0.586160,5.637413,0,1,0,0.034642
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0.044335,6.100671,0.030201,0,0.677852,5.147783,0,1,0,0.044335

In [35]:
# VOLATILITY FEATURES
# Transaction volatility
df['transaction_volatility'] = (
    df.groupby('shopNo')['noOfTrans']
    .transform('std')
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,portability_hub_score,portability_intensity,high_non_local_flag,trans_per_card_FRAUD_DETECTION,units_per_trans_FRAUD_DETECTION,fraud_risk_flag,post_onorc,urban_proxy,distribution_change,transaction_volatility
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,31.461242,0.033702,0,0.898893,3.473515,0,1,0,0.037453,10.639148
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,21.415385,0.041026,0,0.892308,3.588910,0,1,0,0.045889,7.620895
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,16.341297,0.061433,0,0.907850,3.565543,0,1,0,0.067416,4.822785
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,17.268473,0.046798,0,0.908867,3.643243,0,1,0,0.051351,3.258688
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,31.062822,0.033986,0,0.941298,3.547541,0,1,0,0.036066,9.768349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,8.935733,0.028278,0,0.812339,4.413249,0,1,0,0.034700,5.732461
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,82.562791,0.112791,0,0.851163,4.144611,0,1,0,0.132333,20.598454
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,4.595294,0.016471,0,0.656471,4.846429,0,1,0,0.025000,7.309847
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,8.792402,0.020353,0,0.586160,5.637413,0,1,0,0.034642,15.132396
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,6.100671,0.030201,0,0.677852,5.147783,0,1,0,0.044335,11.276409

In [36]:
# Amount volatility
df['amount_volatility'] = (
    df.groupby('shopNo')['totalAmount']
    .transform('std')
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,portability_intensity,high_non_local_flag,trans_per_card_FRAUD_DETECTION,units_per_trans_FRAUD_DETECTION,fraud_risk_flag,post_onorc,urban_proxy,distribution_change,transaction_volatility,amount_volatility
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,0.033702,0,0.898893,3.473515,0,1,0,0.037453,10.639148,0.0
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,0.041026,0,0.892308,3.588910,0,1,0,0.045889,7.620895,0.0
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,0.061433,0,0.907850,3.565543,0,1,0,0.067416,4.822785,0.0
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,0.046798,0,0.908867,3.643243,0,1,0,0.051351,3.258688,0.0
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,0.033986,0,0.941298,3.547541,0,1,0,0.036066,9.768349,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,0.028278,0,0.812339,4.413249,0,1,0,0.034700,5.732461,0.0
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,0.112791,0,0.851163,4.144611,0,1,0,0.132333,20.598454,0.0
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,0.016471,0,0.656471,4.846429,0,1,0,0.025000,7.309847,0.0
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,0.020353,0,0.586160,5.637413,0,1,0,0.034642,15.132396,0.0
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0.030201,0,0.677852,5.147783,0,1,0,0.044335,11.276409,0.0

In [37]:
# Commodity volatility
df['commodity_volatility'] = (
    df.groupby('shopNo')['totalUnits']
    .transform('std')
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,high_non_local_flag,trans_per_card_FRAUD_DETECTION,units_per_trans_FRAUD_DETECTION,fraud_risk_flag,post_onorc,urban_proxy,distribution_change,transaction_volatility,amount_volatility,commodity_volatility
0,1901001,10,2023,932.5,933.5,1365.0,16816.5,0.0,0.0,0.0,...,0,0.898893,3.473515,0,1,0,0.037453,10.639148,0.0,0.000000
1,1901002,10,2023,520.0,522.0,700.0,9798.0,0.0,0.0,0.0,...,0,0.892308,3.588910,0,1,0,0.045889,7.620895,0.0,5.146916
2,1901003,10,2023,266.0,266.0,595.0,4872.0,0.0,0.0,0.0,...,0,0.907850,3.565543,0,1,0,0.067416,4.822785,0.0,2.713868
3,1901004,10,2023,368.0,369.0,490.0,7239.0,10.0,0.0,0.0,...,0,0.908867,3.643243,0,1,0,0.051351,3.258688,0.0,10.891176
4,1901005,10,2023,914.0,914.0,2432.5,16098.0,0.0,0.0,0.0,...,0,0.941298,3.547541,0,1,0,0.036066,9.768349,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482252,4612008,9,2024,316.0,316.0,770.0,6840.0,0.0,0.0,0.0,...,0,0.812339,4.413249,0,1,0,0.034700,5.732461,0.0,60.728601
482253,4612009,9,2024,731.0,732.0,1925.0,15157.0,0.0,0.0,0.0,...,0,0.851163,4.144611,0,1,0,0.132333,20.598454,0.0,67.104860
482254,4612010,9,2024,278.0,279.0,519.0,5730.0,0.0,0.0,0.0,...,0,0.656471,4.846429,0,1,0,0.025000,7.309847,0.0,40.715687
482255,4612011,9,2024,432.0,432.0,1015.0,8766.0,0.0,0.0,0.0,...,0,0.586160,5.637413,0,1,0,0.034642,15.132396,0.0,103.677225
482256,4612012,9,2024,201.0,202.0,70.0,4494.0,0.0,0.0,0.0,...,0,0.677852,5.147783,0,1,0,0.044335,11.276409,0.0,45.359878

In [38]:
# GROWTH FEATURES
df = df.sort_values(
    ['shopNo', 'year', 'month']
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,high_non_local_flag,trans_per_card_FRAUD_DETECTION,units_per_trans_FRAUD_DETECTION,fraud_risk_flag,post_onorc,urban_proxy,distribution_change,transaction_volatility,amount_volatility,commodity_volatility
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,0,0.696532,5.566116,0,1,0,0.140496,20.252507,0.0,35.746906
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,0,0.748555,5.165385,0,1,0,0.157692,20.252507,0.0,35.746906
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,0,0.708092,5.459350,0,1,0,0.162602,20.252507,0.0,35.746906
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,0,0.719653,5.372000,0,1,0,0.136000,20.252507,0.0,35.746906
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,0,0.748555,5.165385,0,1,0,0.188462,20.252507,0.0,35.746906
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,0,0.691275,5.048309,0,1,0,0.033816,11.276409,0.0,45.359878
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,0,0.691275,5.256039,0,1,0,0.048309,11.276409,0.0,45.359878
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,0,0.594118,5.866995,0,1,0,0.024631,11.276409,0.0,45.359878
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,0,0.717791,5.063830,0,1,0,0.055319,11.276409,0.0,45.359878
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,0,0.699387,5.179039,0,1,0,0.030568,11.276409,0.0,45.359878

In [39]:
df.isnull().sum()

shopNo                             0
month                              0
year                               0
noOfRcs                            0
noOfTrans                          0
riceAfsc                           0
riceFsc                            0
riceAap                            0
wheat                              0
sugar                              0
totalAmount                        0
otherShopTransCnt                  0
riceAap_available                  0
wheat_available                    0
totalRcs                           0
totalUnits                         0
units                              0
distCode                           0
distName                           0
officeCode                         0
officeName                         0
longitude                          0
latitude                           0
fpsStatus                          0
fpsType                            0
dateTime                           0
day_name                           0
week                               0
quarter                            0
is_weekend                         0
day_of_year                        0
month_start                        0
month_end                          0
days_in_month                      0
utilization_ratio                  0
units_per_card                     0
amount_per_transaction             0
amount_per_card                    0
rice_afsc_per_trans                0
rice_fsc_per_trans                 0
rice_aap_per_trans                 0
wheat_per_trans                    0
rice_to_wheat_ratio                0
sugar_intensity                    0
wheat_intensity                    0
rice_share                         0
commodity_activity                 0
other_shop_ratio                   0
portability_hub_score              0
portability_intensity              0
high_non_local_flag                0
trans_per_card_FRAUD_DETECTION     0
units_per_trans_FRAUD_DETECTION    0
fraud_risk_flag                    0
post_onorc                         0
urban_proxy                        0
distribution_change                0
transaction_volatility             0
amount_volatility                  0
commodity_volatility               0
dtype: int64

In [40]:
# Amount growth
df['amount_growth'] = df['totalAmount'] / df['totalRcs']
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,trans_per_card_FRAUD_DETECTION,units_per_trans_FRAUD_DETECTION,fraud_risk_flag,post_onorc,urban_proxy,distribution_change,transaction_volatility,amount_volatility,commodity_volatility,amount_growth
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,0.696532,5.566116,0,1,0,0.140496,20.252507,0.0,35.746906,0.0
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,0.748555,5.165385,0,1,0,0.157692,20.252507,0.0,35.746906,0.0
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,0.708092,5.459350,0,1,0,0.162602,20.252507,0.0,35.746906,0.0
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,0.719653,5.372000,0,1,0,0.136000,20.252507,0.0,35.746906,0.0
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,0.748555,5.165385,0,1,0,0.188462,20.252507,0.0,35.746906,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,0.691275,5.048309,0,1,0,0.033816,11.276409,0.0,45.359878,0.0
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,0.691275,5.256039,0,1,0,0.048309,11.276409,0.0,45.359878,0.0
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,0.594118,5.866995,0,1,0,0.024631,11.276409,0.0,45.359878,0.0
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,0.717791,5.063830,0,1,0,0.055319,11.276409,0.0,45.359878,0.0
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,0.699387,5.179039,0,1,0,0.030568,11.276409,0.0,45.359878,0.0

In [41]:
df['amount_growth'].unique()

array([0.        , 0.01388889, 0.02777778, ..., 0.01138952, 0.15629522,
       0.05861071], shape=(42104,))

In [42]:
# Commodity growth
df['commodity_growth'] = (
    df.groupby('shopNo')['totalUnits']
    .pct_change()
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,units_per_trans_FRAUD_DETECTION,fraud_risk_flag,post_onorc,urban_proxy,distribution_change,transaction_volatility,amount_volatility,commodity_volatility,amount_growth,commodity_growth
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,5.566116,0,1,0,0.140496,20.252507,0.0,35.746906,0.0,NaN
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,5.165385,0,1,0,0.157692,20.252507,0.0,35.746906,0.0,-0.002970
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,5.459350,0,1,0,0.162602,20.252507,0.0,35.746906,0.0,0.000000
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,5.372000,0,1,0,0.136000,20.252507,0.0,35.746906,0.0,0.000000
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,5.165385,0,1,0,0.188462,20.252507,0.0,35.746906,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,5.048309,0,1,0,0.033816,11.276409,0.0,45.359878,0.0,0.000000
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,5.256039,0,1,0,0.048309,11.276409,0.0,45.359878,0.0,0.041148
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,5.866995,0,1,0,0.024631,11.276409,0.0,45.359878,0.0,0.094669
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,5.063830,0,1,0,0.055319,11.276409,0.0,45.359878,0.0,-0.000840
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,5.179039,0,1,0,0.030568,11.276409,0.0,45.359878,0.0,-0.003361

In [43]:
df['commodity_growth'] = (
    df['commodity_growth']
    .fillna(0)
)

In [44]:
df['commodity_growth'].isnull().sum()

np.int64(0)

In [45]:
# GEO FEATURES

# Average district activity
df['activity_density'] = (
    df.groupby('distCode')['noOfTrans']
    .transform('mean')
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,fraud_risk_flag,post_onorc,urban_proxy,distribution_change,transaction_volatility,amount_volatility,commodity_volatility,amount_growth,commodity_growth,activity_density
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,0,1,0,0.140496,20.252507,0.0,35.746906,0.0,0.000000,357.852623
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,0,1,0,0.157692,20.252507,0.0,35.746906,0.0,-0.002970,357.852623
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,0,1,0,0.162602,20.252507,0.0,35.746906,0.0,0.000000,357.852623
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,0,1,0,0.136000,20.252507,0.0,35.746906,0.0,0.000000,357.852623
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,0,1,0,0.188462,20.252507,0.0,35.746906,0.0,0.000000,357.852623
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,0,1,0,0.033816,11.276409,0.0,45.359878,0.0,0.000000,374.724798
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,0,1,0,0.048309,11.276409,0.0,45.359878,0.0,0.041148,374.724798
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,0,1,0,0.024631,11.276409,0.0,45.359878,0.0,0.094669,374.724798
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,0,1,0,0.055319,11.276409,0.0,45.359878,0.0,-0.000840,374.724798
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,0,1,0,0.030568,11.276409,0.0,45.359878,0.0,-0.003361,374.724798

In [46]:
# Shop density
df['shop_density'] = (
    df.groupby('distCode')['shopNo']
    .transform('nunique')
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,post_onorc,urban_proxy,distribution_change,transaction_volatility,amount_volatility,commodity_volatility,amount_growth,commodity_growth,activity_density,shop_density
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,1,0,0.140496,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,1,0,0.157692,20.252507,0.0,35.746906,0.0,-0.002970,357.852623,526
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,1,0,0.162602,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,1,0,0.136000,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,1,0,0.188462,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,1,0,0.033816,11.276409,0.0,45.359878,0.0,0.000000,374.724798,301
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,1,0,0.048309,11.276409,0.0,45.359878,0.0,0.041148,374.724798,301
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,1,0,0.024631,11.276409,0.0,45.359878,0.0,0.094669,374.724798,301
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,1,0,0.055319,11.276409,0.0,45.359878,0.0,-0.000840,374.724798,301
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,1,0,0.030568,11.276409,0.0,45.359878,0.0,-0.003361,374.724798,301

In [47]:
# District transaction load
df['district_load'] = (
    df.groupby('distCode')['totalAmount']
    .transform('mean')
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,urban_proxy,distribution_change,transaction_volatility,amount_volatility,commodity_volatility,amount_growth,commodity_growth,activity_density,shop_density,district_load
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,0,0.140496,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,0,0.157692,20.252507,0.0,35.746906,0.0,-0.002970,357.852623,526,153.922816
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,0,0.162602,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,0,0.136000,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,0,0.188462,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,0,0.033816,11.276409,0.0,45.359878,0.0,0.000000,374.724798,301,10.914586
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,0,0.048309,11.276409,0.0,45.359878,0.0,0.041148,374.724798,301,10.914586
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,0,0.024631,11.276409,0.0,45.359878,0.0,0.094669,374.724798,301,10.914586
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,0,0.055319,11.276409,0.0,45.359878,0.0,-0.000840,374.724798,301,10.914586
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,0,0.030568,11.276409,0.0,45.359878,0.0,-0.003361,374.724798,301,10.914586

In [48]:
# SEASONAL FEATURES
# Seasonal demand
df['seasonal_demand'] = (
    df.groupby('month')['noOfTrans']
    .transform('mean')
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,distribution_change,transaction_volatility,amount_volatility,commodity_volatility,amount_growth,commodity_growth,activity_density,shop_density,district_load,seasonal_demand
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,0.140496,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,429.030268
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,0.157692,20.252507,0.0,35.746906,0.0,-0.002970,357.852623,526,153.922816,425.353121
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,0.162602,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,427.492308
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,0.136000,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,432.886564
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,0.188462,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,429.331682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,0.033816,11.276409,0.0,45.359878,0.0,0.000000,374.724798,301,10.914586,429.030268
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,0.048309,11.276409,0.0,45.359878,0.0,0.041148,374.724798,301,10.914586,425.353121
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,0.024631,11.276409,0.0,45.359878,0.0,0.094669,374.724798,301,10.914586,427.492308
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,0.055319,11.276409,0.0,45.359878,0.0,-0.000840,374.724798,301,10.914586,432.886564
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,0.030568,11.276409,0.0,45.359878,0.0,-0.003361,374.724798,301,10.914586,429.331682

In [49]:
# Peak demand month
peak_threshold = (
    df['seasonal_demand']
    .quantile(0.90)
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,distribution_change,transaction_volatility,amount_volatility,commodity_volatility,amount_growth,commodity_growth,activity_density,shop_density,district_load,seasonal_demand
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,0.140496,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,429.030268
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,0.157692,20.252507,0.0,35.746906,0.0,-0.002970,357.852623,526,153.922816,425.353121
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,0.162602,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,427.492308
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,0.136000,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,432.886564
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,0.188462,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,429.331682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,0.033816,11.276409,0.0,45.359878,0.0,0.000000,374.724798,301,10.914586,429.030268
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,0.048309,11.276409,0.0,45.359878,0.0,0.041148,374.724798,301,10.914586,425.353121
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,0.024631,11.276409,0.0,45.359878,0.0,0.094669,374.724798,301,10.914586,427.492308
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,0.055319,11.276409,0.0,45.359878,0.0,-0.000840,374.724798,301,10.914586,432.886564
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,0.030568,11.276409,0.0,45.359878,0.0,-0.003361,374.724798,301,10.914586,429.331682

In [50]:
df['peak_month_flag'] = (
    df['seasonal_demand'] >
    peak_threshold
).astype(int)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,transaction_volatility,amount_volatility,commodity_volatility,amount_growth,commodity_growth,activity_density,shop_density,district_load,seasonal_demand,peak_month_flag
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,429.030268,0
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,20.252507,0.0,35.746906,0.0,-0.002970,357.852623,526,153.922816,425.353121,0
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,427.492308,0
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,432.886564,0
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,429.331682,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,11.276409,0.0,45.359878,0.0,0.000000,374.724798,301,10.914586,429.030268,0
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,11.276409,0.0,45.359878,0.0,0.041148,374.724798,301,10.914586,425.353121,0
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,11.276409,0.0,45.359878,0.0,0.094669,374.724798,301,10.914586,427.492308,0
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,11.276409,0.0,45.359878,0.0,-0.000840,374.724798,301,10.914586,432.886564,0
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,11.276409,0.0,45.359878,0.0,-0.003361,374.724798,301,10.914586,429.331682,0

In [51]:
df['peak_month_flag'] = (
    df['seasonal_demand'] >
    peak_threshold
).astype(int)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,transaction_volatility,amount_volatility,commodity_volatility,amount_growth,commodity_growth,activity_density,shop_density,district_load,seasonal_demand,peak_month_flag
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,429.030268,0
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,20.252507,0.0,35.746906,0.0,-0.002970,357.852623,526,153.922816,425.353121,0
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,427.492308,0
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,432.886564,0
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,20.252507,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,429.331682,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,11.276409,0.0,45.359878,0.0,0.000000,374.724798,301,10.914586,429.030268,0
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,11.276409,0.0,45.359878,0.0,0.041148,374.724798,301,10.914586,425.353121,0
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,11.276409,0.0,45.359878,0.0,0.094669,374.724798,301,10.914586,427.492308,0
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,11.276409,0.0,45.359878,0.0,-0.000840,374.724798,301,10.914586,432.886564,0
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,11.276409,0.0,45.359878,0.0,-0.003361,374.724798,301,10.914586,429.331682,0

In [52]:
# Festival quarter flag
df['festival_quarter'] = (
    df['quarter'].isin([3, 4])
).astype(int)

df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,amount_volatility,commodity_volatility,amount_growth,commodity_growth,activity_density,shop_density,district_load,seasonal_demand,peak_month_flag,festival_quarter
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,429.030268,0,1
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,0.0,35.746906,0.0,-0.002970,357.852623,526,153.922816,425.353121,0,1
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,427.492308,0,1
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,432.886564,0,1
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,0.0,35.746906,0.0,0.000000,357.852623,526,153.922816,429.331682,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,0.0,45.359878,0.0,0.000000,374.724798,301,10.914586,429.030268,0,1
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,0.0,45.359878,0.0,0.041148,374.724798,301,10.914586,425.353121,0,1
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,0.0,45.359878,0.0,0.094669,374.724798,301,10.914586,427.492308,0,1
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,0.0,45.359878,0.0,-0.000840,374.724798,301,10.914586,432.886564,0,1
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,0.0,45.359878,0.0,-0.003361,374.724798,301,10.914586,429.331682,0,1

In [53]:
# SMART SHOP FEATURES
# High performance shops
high_perf_threshold = (
    df['utilization_ratio']
    .quantile(0.90)
)
df['high_performance_shop'] = (
    df['utilization_ratio'] >
    high_perf_threshold
).astype(int)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,commodity_volatility,amount_growth,commodity_growth,activity_density,shop_density,district_load,seasonal_demand,peak_month_flag,festival_quarter,high_performance_shop
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,35.746906,0.0,0.000000,357.852623,526,153.922816,429.030268,0,1,0
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,35.746906,0.0,-0.002970,357.852623,526,153.922816,425.353121,0,1,0
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,35.746906,0.0,0.000000,357.852623,526,153.922816,427.492308,0,1,0
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,35.746906,0.0,0.000000,357.852623,526,153.922816,432.886564,0,1,0
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,35.746906,0.0,0.000000,357.852623,526,153.922816,429.331682,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,45.359878,0.0,0.000000,374.724798,301,10.914586,429.030268,0,1,0
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,45.359878,0.0,0.041148,374.724798,301,10.914586,425.353121,0,1,0
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,45.359878,0.0,0.094669,374.724798,301,10.914586,427.492308,0,1,0
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,45.359878,0.0,-0.000840,374.724798,301,10.914586,432.886564,0,1,0
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,45.359878,0.0,-0.003361,374.724798,301,10.914586,429.331682,0,1,0

In [54]:
# Low activity shops
low_activity_threshold = (
    df['utilization_ratio']
    .quantile(0.10)
)

df['low_activity_shop']=(
    df['utilization_ratio']<
    low_activity_threshold
).astype(int)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,amount_growth,commodity_growth,activity_density,shop_density,district_load,seasonal_demand,peak_month_flag,festival_quarter,high_performance_shop,low_activity_shop
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,0.0,0.000000,357.852623,526,153.922816,429.030268,0,1,0,0
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,0.0,-0.002970,357.852623,526,153.922816,425.353121,0,1,0,0
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,0.0,0.000000,357.852623,526,153.922816,427.492308,0,1,0,0
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,0.0,0.000000,357.852623,526,153.922816,432.886564,0,1,0,0
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,0.0,0.000000,357.852623,526,153.922816,429.331682,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,0.0,0.000000,374.724798,301,10.914586,429.030268,0,1,0,0
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,0.0,0.041148,374.724798,301,10.914586,425.353121,0,1,0,0
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,0.0,0.094669,374.724798,301,10.914586,427.492308,0,1,0,1
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,0.0,-0.000840,374.724798,301,10.914586,432.886564,0,1,0,0
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,0.0,-0.003361,374.724798,301,10.914586,429.331682,0,1,0,0

In [55]:
# High revenue shops
high_revenue_threshold=(
    df['totalAmount'].quantile(0.90)
)

df['high_revenue_shop'] = (
    df['totalAmount'] >
    high_revenue_threshold
).astype(int)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,commodity_growth,activity_density,shop_density,district_load,seasonal_demand,peak_month_flag,festival_quarter,high_performance_shop,low_activity_shop,high_revenue_shop
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,0.000000,357.852623,526,153.922816,429.030268,0,1,0,0,0
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,-0.002970,357.852623,526,153.922816,425.353121,0,1,0,0,0
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,0.000000,357.852623,526,153.922816,427.492308,0,1,0,0,0
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,0.000000,357.852623,526,153.922816,432.886564,0,1,0,0,0
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,0.000000,357.852623,526,153.922816,429.331682,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,0.000000,374.724798,301,10.914586,429.030268,0,1,0,0,0
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,0.041148,374.724798,301,10.914586,425.353121,0,1,0,0,0
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,0.094669,374.724798,301,10.914586,427.492308,0,1,0,1,0
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,-0.000840,374.724798,301,10.914586,432.886564,0,1,0,0,0
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,-0.003361,374.724798,301,10.914586,429.331682,0,1,0,0,0

In [56]:
# AVAILABILITY FEATURES
# Commodity availability score
df['availability_score'] = (
    df['riceAap_available'] +
    df['wheat_available']
)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,activity_density,shop_density,district_load,seasonal_demand,peak_month_flag,festival_quarter,high_performance_shop,low_activity_shop,high_revenue_shop,availability_score
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,357.852623,526,153.922816,429.030268,0,1,0,0,0,0
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,357.852623,526,153.922816,425.353121,0,1,0,0,0,0
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,357.852623,526,153.922816,427.492308,0,1,0,0,0,0
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,357.852623,526,153.922816,432.886564,0,1,0,0,0,0
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,357.852623,526,153.922816,429.331682,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,374.724798,301,10.914586,429.030268,0,1,0,0,0,0
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,374.724798,301,10.914586,425.353121,0,1,0,0,0,0
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,374.724798,301,10.914586,427.492308,0,1,0,1,0,0
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,374.724798,301,10.914586,432.886564,0,1,0,0,0,0
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,374.724798,301,10.914586,429.331682,0,1,0,0,0,0

In [57]:
# STATUS FEATURES
# Active FPS indicator
df['active_fps'] = (
    df['fpsStatus']
    .astype(str)
    .str.lower()
    .isin(['active', 'running'])
).astype(int)

df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,shop_density,district_load,seasonal_demand,peak_month_flag,festival_quarter,high_performance_shop,low_activity_shop,high_revenue_shop,availability_score,active_fps
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,526,153.922816,429.030268,0,1,0,0,0,0,1
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,526,153.922816,425.353121,0,1,0,0,0,0,1
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,526,153.922816,427.492308,0,1,0,0,0,0,1
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,526,153.922816,432.886564,0,1,0,0,0,0,1
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,526,153.922816,429.331682,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,301,10.914586,429.030268,0,1,0,0,0,0,1
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,301,10.914586,425.353121,0,1,0,0,0,0,1
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,301,10.914586,427.492308,0,1,0,1,0,0,1
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,301,10.914586,432.886564,0,1,0,0,0,0,1
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,301,10.914586,429.331682,0,1,0,0,0,0,1

In [58]:
 #LOCATION FEATURES
# Missing geo flag
df['missing_geo_flag'] = (
    df['longitude'].isnull() |
    df['latitude'].isnull()
).astype(int)
df

,shopNo,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,...,district_load,seasonal_demand,peak_month_flag,festival_quarter,high_performance_shop,low_activity_shop,high_revenue_shop,availability_score,active_fps,missing_geo_flag
89902,1407001,1,2023,241.0,241.0,805.0,4550.0,0.0,0.0,0.0,...,153.922816,429.030268,0,1,0,0,0,0,1,0
141574,1407001,2,2023,258.0,259.0,910.0,4840.0,0.0,0.0,0.0,...,153.922816,425.353121,0,1,0,0,0,0,1,0
193223,1407001,3,2023,245.0,245.0,840.0,4735.0,0.0,0.0,0.0,...,153.922816,427.492308,0,1,0,0,0,0,1,0
244897,1407001,4,2023,246.0,249.0,840.0,5592.0,0.0,0.0,0.0,...,153.922816,432.886564,0,1,0,0,0,0,1,0
296587,1407001,5,2023,258.0,259.0,840.0,5970.0,0.0,0.0,0.0,...,153.922816,429.331682,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137811,4612012,1,2025,204.0,206.0,70.0,4590.0,0.0,0.0,0.0,...,10.914586,429.030268,0,1,0,0,0,0,1,0
189452,4612012,2,2025,202.0,206.0,35.0,4818.0,0.0,0.0,0.0,...,10.914586,425.353121,0,1,0,0,0,0,1,0
241126,4612012,3,2025,201.0,202.0,70.0,4566.0,0.0,0.0,0.0,...,10.914586,427.492308,0,1,0,1,0,0,1,0
292816,4612012,4,2025,232.0,234.0,70.0,5418.0,0.0,0.0,0.0,...,10.914586,432.886564,0,1,0,0,0,0,1,0
344492,4612012,5,2025,227.0,228.0,70.0,5310.0,0.0,0.0,0.0,...,10.914586,429.331682,0,1,0,0,0,0,1,0

In [61]:
df.shape

(482257, 74)

In [60]:
print("Advanced Feature Engineering Completed Successfully")

Advanced Feature Engineering Completed Successfully

In [62]:
df.to_csv("../data/Master_data/Feature_Engineering_dataset.csv", index=False)
print("Feature Engineering data save Successfully")

Feature Engineering data save Successfully

In [63]:
df.shape

(482257, 74)