In [1]:
import pandas as pd
import numpy as np

In [2]:
#Load dataset
df=pd.read_csv("../data/Master_data/Encoding_data.csv")
print(df.head)

<bound method NDFrame.head of          shopNo  month  year   noOfRcs  noOfTrans  riceAfsc   riceFsc  \
0       1407001      1  2023  1.870099   1.870099  2.040192  2.243164
1       1407001      2  2023  1.880507   1.881095  2.055986  2.249699
2       1407001      3  2023  1.872622   1.872622  2.045703  2.247384
3       1407001      4  2023  1.873245   1.875098  2.045703  2.264808
4       1407001      5  2023  1.880507   1.881095  2.045703  2.271576
...         ...    ...   ...       ...        ...       ...       ...
482112  4612012      1  2025  1.844195   1.845730  1.660640  2.244093
482113  4612012      2  2025  1.842644   1.845730  1.522467  2.249218
482114  4612012      3  2025  1.841861   1.842644  1.660640  2.243537
482115  4612012      4  2025  1.864241   1.865565  1.660640  2.261520
482116  4612012      5  2025  1.860873   1.861553  1.660640  2.259420

        riceAap  wheat  sugar  ...  peak_month_flag  festival_quarter  \
0           0.0    0.0    0.0  ...                0                 1
1           0.0    0.0    0.0  ...                0                 1
2           0.0    0.0    0.0  ...                0                 1
3           0.0    0.0    0.0  ...                0                 1
4           0.0    0.0    0.0  ...                0                 1
...         ...    ...    ...  ...              ...               ...
482112      0.0    0.0    0.0  ...                0                 1
482113      0.0    0.0    0.0  ...                0                 1
482114      0.0    0.0    0.0  ...                0                 1
482115      0.0    0.0    0.0  ...                0                 1
482116      0.0    0.0    0.0  ...                0                 1

        high_performance_shop  low_activity_shop  high_revenue_shop  \
0                           0                  0                  0
1                           0                  0                  0
2                           0                  0                  0
3                           0                  0                  0
4                           0                  0                  0
...                       ...                ...                ...
482112                      0                  0                  0
482113                      0                  0                  0
482114                      0                  1                  0
482115                      0                  0                  0
482116                      0                  0                  0

        availability_score  active_fps  missing_geo_flag  rice_wheat_ratio  \
0                      0.0           1                 0          2.040192
1                      0.0           1                 0          2.055986
2                      0.0           1                 0          2.045703
3                      0.0           1                 0          2.045703
4                      0.0           1                 0          2.045703
...                    ...         ...               ...               ...
482112                 0.0           1                 0          1.660640
482113                 0.0           1                 0          1.522467
482114                 0.0           1                 0          1.660640
482115                 0.0           1                 0          1.660640
482116                 0.0           1                 0          1.660640

        distName_freq
0               14161
1               14161
2               14161
3               14161
4               14161
...               ...
482112           8412
482113           8412
482114           8412
482115           8412
482116           8412

[482117 rows x 72 columns]>

In [3]:
df.shape

(482117, 72)

In [4]:
df.columns

Index(['shopNo', 'month', 'year', 'noOfRcs', 'noOfTrans', 'riceAfsc',
       'riceFsc', 'riceAap', 'wheat', 'sugar', 'totalAmount',
       'otherShopTransCnt', 'riceAap_available', 'wheat_available', 'totalRcs',
       'totalUnits', 'units', 'distCode', 'officeCode', 'longitude',
       'latitude', 'fpsStatus', 'fpsType', 'week', 'quarter', 'is_weekend',
       'day_of_year', 'month_start', 'month_end', 'days_in_month',
       'utilization_ratio', 'units_per_card', 'amount_per_transaction',
       'amount_per_card', 'rice_afsc_per_trans', 'rice_fsc_per_trans',
       'rice_aap_per_trans', 'wheat_per_trans', 'rice_to_wheat_ratio',
       'sugar_intensity', 'wheat_intensity', 'rice_share',
       'commodity_activity', 'other_shop_ratio', 'portability_hub_score',
       'portability_intensity', 'high_non_local_flag',
       'trans_per_card_FRAUD_DETECTION', 'units_per_trans_FRAUD_DETECTION',
       'fraud_risk_flag', 'post_onorc', 'urban_proxy', 'distribution_change',
       'transaction_volatility', 'amount_volatility', 'commodity_volatility',
       'amount_growth', 'commodity_growth', 'activity_density', 'shop_density',
       'district_load', 'seasonal_demand', 'peak_month_flag',
       'festival_quarter', 'high_performance_shop', 'low_activity_shop',
       'high_revenue_shop', 'availability_score', 'active_fps',
       'missing_geo_flag', 'rice_wheat_ratio', 'distName_freq'],
      dtype='object')

In [5]:
#These are IDs / identifiers.
drop_cols = [
    'shopNo',
    'distCode',
    'officeCode'
]

# Drop columns
df = df.drop(columns=drop_cols, errors='ignore')

# Check remaining columns
print(df.shape)
df.head()

(482117, 69)

,month,year,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,totalAmount,...,peak_month_flag,festival_quarter,high_performance_shop,low_activity_shop,high_revenue_shop,availability_score,active_fps,missing_geo_flag,rice_wheat_ratio,distName_freq
0,1,2023,1.870099,1.870099,2.040192,2.243164,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0.0,1,0,2.040192,14161
1,2,2023,1.880507,1.881095,2.055986,2.249699,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0.0,1,0,2.055986,14161
2,3,2023,1.872622,1.872622,2.045703,2.247384,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0.0,1,0,2.045703,14161
3,4,2023,1.873245,1.875098,2.045703,2.264808,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0.0,1,0,2.045703,14161
4,5,2023,1.880507,1.881095,2.045703,2.271576,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0.0,1,0,2.045703,14161

In [6]:
df.shape

(482117, 69)

In [7]:
for col in drop_cols:
    print(col, "→", col in df.columns)

shopNo → False
distCode → False
officeCode → False

In [8]:
#step 2:-These are useful for seasonality patterns.
time_cols = [
    'month',
    'year',
    'week',
    'quarter',
    'day_of_year',
    'days_in_month'
]

In [9]:
#scaling Times..
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df[time_cols] = scaler.fit_transform(df[time_cols])

df[time_cols].head()

      month      year  week  quarter  day_of_year  days_in_month
0 -1.385245 -1.017165   0.0      0.0          0.0            0.0
1 -1.093639 -1.017165   0.0      0.0          0.0            0.0
2 -0.802034 -1.017165   0.0      0.0          0.0            0.0
3 -0.510428 -1.017165   0.0      0.0          0.0            0.0
4 -0.218822 -1.017165   0.0      0.0          0.0            0.0

In [10]:
#Useful for regional clustering.
geo_cols = [
    'longitude',
    'latitude'
]

In [11]:
from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()

df[geo_cols] = scaler.fit_transform(df[geo_cols])

df[geo_cols].head()

   longitude  latitude
0  -1.346759 -1.215867
1  -1.346759 -1.215867
2  -1.346759 -1.215867
3  -1.346759 -1.215867
4  -1.346759 -1.215867

In [12]:
df[['longitude', 'latitude']].describe().T

,count,mean,std,min,25%,50%,75%,max
longitude,482117.0,-9.149334e-16,1.000001,-1.976285,-0.748854,-0.172526,0.776021,2.97713
latitude,482117.0,-6.768620e-15,1.000001,-2.317987,-0.681013,-0.137363,0.729542,2.64039

In [14]:
# CONTINUOUS NUMERIC FEATURES (Scale)
continuous_cols = [
    'noOfRcs',
    'noOfTrans',
    'riceAfsc',
    'riceFsc',
    'riceAap',
    'wheat',
    'sugar',
    'totalAmount',
    'otherShopTransCnt',
    'riceAap_available',
    'wheat_available',
    'totalRcs',
    'totalUnits',
    'units',
    'utilization_ratio',
    'units_per_card',
    'amount_per_transaction',
    'amount_per_card',
    'rice_afsc_per_trans',
    'rice_fsc_per_trans',
    'rice_aap_per_trans',
    'wheat_per_trans',
    'rice_to_wheat_ratio',
    'sugar_intensity',
    'wheat_intensity',
    'rice_share',
    'commodity_activity',
    'other_shop_ratio',
    'portability_hub_score',
    'portability_intensity',
    'trans_per_card_FRAUD_DETECTION',
    'units_per_trans_FRAUD_DETECTION',
    'distribution_change',
    'transaction_volatility',
    'amount_volatility',
    'commodity_volatility',
    'amount_growth',
    'commodity_growth',
    'activity_density',
    'shop_density',
    'district_load',
    'seasonal_demand',
    'availability_score',
    'rice_wheat_ratio',
    'distName_freq'
]

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df[continuous_cols] = scaler.fit_transform(
    df[continuous_cols]
)

df[continuous_cols].head()

,noOfRcs,noOfTrans,riceAfsc,riceFsc,riceAap,wheat,sugar,totalAmount,otherShopTransCnt,riceAap_available,...,commodity_volatility,amount_growth,commodity_growth,activity_density,shop_density,district_load,seasonal_demand,availability_score,rice_wheat_ratio,distName_freq
0,-0.713706,-0.718301,0.048610,-0.458836,-0.271319,-0.285129,-0.34789,-0.381175,-0.184826,-0.280723,...,1.065791,-0.261387,-0.090344,-0.686356,-0.17029,0.631069,0.154939,-0.402903,0.285560,-0.419771
1,-0.593218,-0.590942,0.141764,-0.372330,-0.271319,-0.285129,-0.34789,-0.381175,-0.062457,-0.280723,...,1.065791,-0.261387,-0.288215,-0.686356,-0.17029,0.631069,-1.461163,-0.402903,0.318854,-0.419771
2,-0.684496,-0.689076,0.081113,-0.402973,-0.271319,-0.285129,-0.34789,-0.381175,-0.078358,-0.280723,...,1.065791,-0.261387,-0.090344,-0.686356,-0.17029,0.631069,-0.520993,-0.402903,0.297176,-0.419771
3,-0.677279,-0.660393,0.081113,-0.172304,-0.271319,-0.285129,-0.34789,-0.381175,-0.184826,-0.280723,...,1.065791,-0.261387,-0.090344,-0.686356,-0.17029,0.631069,1.849777,-0.402903,0.297176,-0.419771
4,-0.593218,-0.590942,0.081113,-0.082694,-0.271319,-0.285129,-0.34789,-0.381175,0.050237,-0.280723,...,1.065791,-0.261387,-0.090344,-0.686356,-0.17029,0.631069,0.287410,-0.402903,0.297176,-0.419771

In [16]:
df.describe().T[['mean', 'std', 'min', 'max']]

                            mean       std        min       max
month              -4.500977e-17  1.000001  -1.385245  1.822417
year               -1.452570e-13  1.000001  -1.017165  1.692703
noOfRcs             1.350706e-15  1.000001 -16.266571  1.474271
noOfTrans           1.192243e-15  1.000001 -16.279742  1.472463
riceAfsc           -5.885757e-16  1.000001 -11.983954  0.840260
...                          ...       ...        ...       ...
availability_score -1.131876e-16  1.000001  -0.402903  3.964164
active_fps          9.913029e-01  0.092852   0.000000  1.000000
missing_geo_flag    0.000000e+00  0.000000   0.000000  0.000000
rice_wheat_ratio   -3.772921e-17  1.000001  -4.014988  0.568502
distName_freq       6.036674e-17  1.000001  -1.869082  2.077714

[69 rows x 4 columns]

In [17]:
df.to_csv("../data/Master_data/scaled_data.csv",index=False)

In [18]:
df.shape

(482117, 69)

In [19]:
import joblib
# Save scaled data as PKL
joblib.dump(df,"../model/scaled_data.pkl")

print("Scaled data saved successfully!")

Scaled data saved successfully!